### ISSUE TITLE
App doesn't start on Galaxy Note III

### ISSUE THREAD

**Issue by mmazi** [bsimic0001/AegisWallet#40]
This used to work and I have some coins in the wallet, but now the app, when started, first just displays a black screen for say 20 seconds, then crashes. So I can't access my coins.

I've seen a Galaxy Note 4 user complain about the same symptoms on Google Play (first in February, then again in May 2015).

**Comment by bsimic0001** [comment]
Can you send me a screen shot  or recording of the issue perhaps? It would help a lot. I'll check the logs on my end as well to try to figure it out. If you have a backup and need the BTC right away, I should be able to recover your funds using the fund recovery feature. Just email it to me at bojan@bitcoinsecurityproject.org

**Comment by mmazi** [comment]
Well, the screenshot would be just black; a video wouldn't reveal much more than what I described. After many seconds of a black screen (where the phone still responds normally otherwise, eg. the home button  etc.), I get the message that the app has crashed and the option to send a report to Google (which I did, but I'm not sure if the app author gets this report).

Can I send you some logs or something?

**Comment by bsimic0001** [comment]
Ok I see the bug in the crash report you provided. I should be able to issue a fix in the next day or two. 

Thanks a lot!

**Comment by mmazi** [comment]
Thanks for the quick response. Any progress yet?

I submitted another crash report a few days ago. Is there anything else I can do?

**Comment by bsimic0001** [comment]
Hey there. I just submitted a fix to Google Play. It should be available for download within 6 hours. Please let me know if it fixes your issue.

**Comment by mmazi** [comment]
Aegis Wallet now starts normally -- thanks a lot for fixing this!
