### ISSUE TITLE
Unable to send BTC

### ISSUE THREAD

**Issue by nextux** [bsimic0001/AegisWallet#42]
Wallet won't send BTC on a device running Android N.

Wallet decrypted or encypted.
1. Open Aegis Wallet
2. Select Red Sent Button
3. Scan or enter BTC address
4. Type in amount in currency or BTC
5. Add Note (or ignore note)
6. Press Send
7. Does nothing.

**Comment by bsimic0001** [comment]
Chances are that you're sending an amount thats smaller than the amount + minimum transaction fee.
