### ISSUE TITLE
Add ability to export Private Keys

### ISSUE THREAD

**Issue by gahenderson85** [bsimic0001/AegisWallet#43]
Whether the wallet is encrypted or decrypted the backup seems to always export keys that are encrypted.

Please add the ability to directly export private keys.

**Comment by SeanReardon** [comment]
Please!  Would love this feature!!

**Comment by bsimic0001** [comment]
Look for it within 24 hours. It will be in the "BACKUP DEBUG" menu.

**Comment by gahenderson85** [comment]
Thanks so much for taking time to add this feature, I attempted to build and modify your repo myself but got stuck with android studio / gradle conversion conflicts.

**Comment by gahenderson85** [comment]
Were the recent changes pushed out to Google Play? I see you noted revisions were released on Issue #44 , however Google Play show's no new releases and I am running the most recent version.

**Comment by bsimic0001** [comment]
It should be available within a few minutes. Give it a shot and let me
know!

**Comment by gahenderson85** [comment]
Works like a charm! Thanks again for pushing out the update.

**Comment by bsimic0001** [comment]
Glad to help!!
