### ISSUE TITLE
Because transaction fee is hardcoded, and you can't export private key, Aegis wallet eventually turns into an unretrievable btc sink

### ISSUE THREAD

**Issue by SeanReardon** [bsimic0001/AegisWallet#44]
This is currently the case, not theoretical.

It appears that Aegis provides a hardcoded transaction fee of 44 Satoshi per byte.

Looking at https://bitcoinfees.21.co, you can see that 44 s/b effectively puts such a transaction into "indefinite" delay.

By comparison, MyCelium allows the sender to choose amongst a variety of transaction priorities, which map to different s/b.  Those mappings appear to be updated fairly regularly, so that "fast" always works out as fast, regardless of market prices.

As is, the btc that are in my Aegis wallet are now trapped until:

1.  Aegis updates with a feature where transaction fees make more sense (or are directly input by the user.)

2.  Aegis updates with a feature that allows me to export the private key, so that I can switch to a wallet that doesn't suffer from the lack of this feature.

3.  The market for transaction fees drops down below the hardcoded value of 44 s/b.

Help!

**Comment by bsimic0001** [comment]
This has been fixed in a new version just released. For now, the fee is just increased to 50K Satoshi's per KB in the tx. Will add modifiable transaction fee amounts later.
